name: CI Tutorial

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - deploy

jobs:
  "run-jest-tests":
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          path: repo

      - name: Debug Environment
        run: |
          echo "Current directory: $(pwd)"
          echo "GitHub workspace: $GITHUB_WORKSPACE"
          ls -la

      - name: Install Dependencies
        working-directory: ./repo
        run: npm install

      - name: Run Tests
        working-directory: ./repo
        run: npm run test
